services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appnotes-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.vxnjsbfmyzsqfuzfmloq.supabase.co:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Kz9L1HIJfqXUZzmF
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
